# @package _global_
defaults:
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.05
  betas: [0.9, 0.95]
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${eval:'${trainer.max_epochs} * ${trainer.num_model_updates}'}
  _partial_: true
